name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Zip
      run: |
        zip -r jMS-Resource-Pack *
        sha1sum -b jMS-Resource-Pack.zip > jMS-Resource-Pack.zip.sha1

    - name: Upload Release Zip
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./jMS-Resource-Pack.zip
        asset_name: jMS-Resource-Pack.zip
        asset_content_type: application/zip

    - name: Upload Release SHA1
      id: upload-release-asset-sha1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./jMS-Resource-Pack.zip.sha1
        asset_name: jMS-Resource-Pack.zip.sha1
        asset_content_type: text/plain
