name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip
      run: |
        zip -r jMS-Resource-Pack *
        sha1sum -b jMS-Resource-Pack.zip > jMS-Resource-Pack.zip.sha1

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Get commit summary
      id: get_commit_summary
      run: |
        PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
        echo "PREVIOUS_TAG: $PREVIOUS_TAG"
        COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
        COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
        echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}
        draft: false
        prerelease: false

    - name: Upload Release Zip
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./jMS-Resource-Pack.zip
        asset_name: jMS-Resource-Pack.zip
        asset_content_type: application/zip

    - name: Upload Release SHA1
      id: upload-release-asset-sha1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./jMS-Resource-Pack.zip.sha1
        asset_name: jMS-Resource-Pack.zip.sha1
        asset_content_type: text/plain